/**
 * ================================================================
 *  AI FLIGHT DEAL ORCHESTRATOR
 *
 *  Not a search engine. An agent that plans a research strategy,
 *  executes it, reports exactly what it could and could not check,
 *  and ranks by YOUR priorities — then sends you to a named,
 *  trusted booking channel.
 * ================================================================
 *
 *  NORTH STAR
 *    Success is not flights found or providers connected.
 *    Success is: websites you no longer need to open,
 *    time saved before deciding, and confidence when you click
 *    "Book with <named channel>".
 *
 *  BINDINGS
 *    Secret  TRAVELPAYOUTS_TOKEN   required
 *    Secret  GEMINI_API_KEY        optional (narration only)
 *    Var     TP_MARKER             optional
 *    Var     DEFAULT_MARKET        optional, default "hk"
 *    KV      HISTORY               optional but strongly recommended
 *
 *  HARD RULES ENFORCED IN CODE
 *    1. No price is ever generated by an LLM.
 *    2. No future promotion is ever predicted. Signals only, labelled.
 *    3. Every step that did not run reports WHY NOT.
 *    4. Confidence is never a single blended number.
 *    5. Buttons name their channel. "Book Now" does not exist.
 */

const TP = "https://api.travelpayouts.com";

/* ================================================================
 * TRAVELLER PROFILES
 * One formula cannot serve a backpacker and a business traveller.
 * Profiles set the starting weights; the preference quiz refines them.
 * ================================================================ */

const PROFILES = {
  backpacker: {
    id: "backpacker",
    timeValue: 40,        // HKD per hour of extra travel time
    stopPenalty: 60,      // HKD per connection
    channelPremium: 80,   // HKD extra you'd pay to book airline-direct
    maxGroundHours: 8,    // hard filter on ground transfer
    maxStops: 3,
  },
  balanced: {
    id: "balanced",
    timeValue: 120, stopPenalty: 150, channelPremium: 200,
    maxGroundHours: 4, maxStops: 2,
  },
  family: {
    id: "family",
    timeValue: 200, stopPenalty: 400, channelPremium: 300,
    maxGroundHours: 3, maxStops: 1,
  },
  business: {
    id: "business",
    timeValue: 500, stopPenalty: 600, channelPremium: 400,
    maxGroundHours: 1.5, maxStops: 1,
  },
};

/**
 * PREFERENCE QUIZ
 * Nobody can answer "what is an hour worth to you in HKD".
 * Everyone can answer "would you spend 2 more hours to save $500".
 * Each answer brackets timeValue; we converge on a real number.
 */
const QUIZ = [
  { id: "q1", kind: "time", hours: 2, save: 500,
    zh: "你願唔願意多花 2 個鐘,慳 HK$500?", en: "Spend 2 extra hours to save HK$500?" },
  { id: "q2", kind: "time", hours: 4, save: 600,
    zh: "多花 4 個鐘,慳 HK$600 呢?", en: "Spend 4 extra hours to save HK$600?" },
  { id: "q3", kind: "stop", save: 300,
    zh: "轉一次機(唔係直航),慳 HK$300,你肯唔肯?", en: "Take 1 stop instead of direct to save HK$300?" },
  { id: "q4", kind: "channel", save: 400,
    zh: "經一間你未聽過嘅代理訂票,慳 HK$400,你肯唔肯?", en: "Book via an agency you've never heard of to save HK$400?" },
];

/**
 * Derive weights from quiz answers. Each time-question gives a bound:
 * "yes" → timeValue <= save/hours ;  "no" → timeValue >= save/hours
 */
function weightsFromAnswers(answers, base) {
  const w = { ...(base || PROFILES.balanced) };
  let lo = 0, hi = 2000, bounded = false;

  for (const q of QUIZ) {
    const a = answers[q.id];
    if (a === undefined) continue;
    if (q.kind === "time") {
      const rate = q.save / q.hours;
      if (a === true) { hi = Math.min(hi, rate); bounded = true; }
      else { lo = Math.max(lo, rate); bounded = true; }
    }
    if (q.kind === "stop") w.stopPenalty = a === true ? Math.min(w.stopPenalty, q.save) : Math.max(w.stopPenalty, q.save + 100);
    if (q.kind === "channel") w.channelPremium = a === true ? Math.min(w.channelPremium, q.save) : Math.max(w.channelPremium, q.save + 100);
  }

  if (bounded) {
    if (lo > hi) w.timeValue = Math.round((lo + hi) / 2);      // inconsistent answers → midpoint
    else if (hi < 2000 && lo > 0) w.timeValue = Math.round((lo + hi) / 2);
    else if (hi < 2000) w.timeValue = Math.round(hi * 0.75);
    else w.timeValue = Math.round(lo * 1.25);
  }
  w.derivedFrom = bounded ? "quiz" : "profile";
  w.bounds = bounded ? { lo, hi } : null;
  return w;
}

/* ================================================================
 * BOOKING CHANNELS — every button names its destination
 * ================================================================ */

const AIRLINE_SITES = {
  CX:{n:"Cathay Pacific",z:"國泰航空",u:"https://www.cathaypacific.com/cx/en_HK/book-a-trip.html"},
  UO:{n:"HK Express",z:"HK Express",u:"https://www.hkexpress.com/en-hk/"},
  HX:{n:"Hong Kong Airlines",z:"香港航空",u:"https://www.hongkongairlines.com/en_HK/homepage"},
  SQ:{n:"Singapore Airlines",z:"新加坡航空",u:"https://www.singaporeair.com/"},
  TR:{n:"Scoot",u:"https://www.flyscoot.com/"},
  NH:{n:"ANA",z:"全日空",u:"https://www.ana.co.jp/en/us/"},
  JL:{n:"Japan Airlines",z:"日本航空",u:"https://www.jal.co.jp/en/"},
  MM:{n:"Peach",u:"https://www.flypeach.com/en"},
  KE:{n:"Korean Air",z:"大韓航空",u:"https://www.koreanair.com/"},
  OZ:{n:"Asiana Airlines",z:"韓亞航空",u:"https://flyasiana.com/"},
  "7C":{n:"Jeju Air",u:"https://www.jejuair.net/en/main/base/main.do"},
  TW:{n:"T'way Air",u:"https://www.twayair.com/app/main"},
  BR:{n:"EVA Air",z:"長榮航空",u:"https://www.evaair.com/"},
  CI:{n:"China Airlines",z:"中華航空",u:"https://www.china-airlines.com/"},
  AK:{n:"AirAsia",u:"https://www.airasia.com/"},
  FD:{n:"Thai AirAsia",u:"https://www.airasia.com/"},
  D7:{n:"AirAsia X",u:"https://www.airasia.com/"},
  TG:{n:"Thai Airways",z:"泰國航空",u:"https://www.thaiairways.com/"},
  VN:{n:"Vietnam Airlines",u:"https://www.vietnamairlines.com/"},
  VJ:{n:"VietJet Air",u:"https://www.vietjetair.com/"},
  PR:{n:"Philippine Airlines",u:"https://www.philippineairlines.com/"},
  "5J":{n:"Cebu Pacific",u:"https://www.cebupacificair.com/"},
  MH:{n:"Malaysia Airlines",z:"馬來西亞航空",u:"https://www.malaysiaairlines.com/"},
  GA:{n:"Garuda Indonesia",u:"https://www.garuda-indonesia.com/"},
  EK:{n:"Emirates",z:"阿聯酋航空",u:"https://www.emirates.com/"},
  QR:{n:"Qatar Airways",z:"卡塔爾航空",u:"https://www.qatarairways.com/"},
  TK:{n:"Turkish Airlines",u:"https://www.turkishairlines.com/"},
  BA:{n:"British Airways",u:"https://www.britishairways.com/"},
  AF:{n:"Air France",u:"https://www.airfrance.com/"},
  LH:{n:"Lufthansa",u:"https://www.lufthansa.com/"},
  KL:{n:"KLM",u:"https://www.klm.com/"},
  UA:{n:"United Airlines",u:"https://www.united.com/"},
  AA:{n:"American Airlines",u:"https://www.aa.com/"},
  DL:{n:"Delta Air Lines",u:"https://www.delta.com/"},
  QF:{n:"Qantas",u:"https://www.qantas.com/"},
  CZ:{n:"China Southern",z:"中國南方航空",u:"https://www.csair.com/"},
  MU:{n:"China Eastern",z:"中國東方航空",u:"https://us.ceair.com/"},
  CA:{n:"Air China",z:"中國國際航空",u:"https://www.airchina.us/"},
};

// Agency reputation tiers → channelPremium multiplier.
const AGENCY_TIER = {
  "Trip.com":1, "Ctrip":1, "Expedia":1, "Booking.com":1, "Priceline":1,
  "Kiwi.com":2, "eDreams":2, "Gotogate":2, "Mytrip":2, "Kayak":1,
};
function agencyTier(name) {
  if (!name) return { tier: 3, label: "unknown agency" };
  for (const k of Object.keys(AGENCY_TIER)) {
    if (name.toLowerCase().includes(k.toLowerCase())) return { tier: AGENCY_TIER[k], label: name };
  }
  return { tier: 3, label: name };
}

const dm = (i) => i.slice(8,10) + i.slice(5,7);
const ymd = (i) => i.slice(2,4) + i.slice(5,7) + i.slice(8,10);

/**
 * Channels for one itinerary. Labels are claims the code must earn:
 * an airline name only appears when the carrier code is verified.
 */
function channels(o, marker, pax) {
  const out = [];
  if (!o.origin || !o.destination || !o.departDate) return out;
  const air = o.airlineCode && AIRLINE_SITES[o.airlineCode];

  if (air) out.push({
    id: "airline", kind: "book", tier: 0,
    nameZh: "直接向" + (air.z || air.n) + "訂票(官網)", nameEn: "Book with " + air.n + " (Official)",
    url: air.u, datesPrefilled: false,
  });

  const ag = agencyTier(o.agency);
  if (o.agency) out.push({
    id: "agency", kind: "book", tier: ag.tier,
    nameZh: "經 " + ag.label + " 訂票", nameEn: "Book with " + ag.label,
    url: null, agencyOnly: true,
  });

  let seg = o.origin + dm(o.departDate) + o.destination;
  if (o.returnDate) seg += dm(o.returnDate);
  seg += String(pax || 1);
  out.push({
    id: "aviasales", kind: "compare", tier: null,
    nameZh: "比較訂票渠道", nameEn: "Compare booking options",
    url: "https://www.aviasales.com/search/" + seg + (marker ? "?marker=" + marker : ""),
    isPriceSource: true, datesPrefilled: true,
  });

  const gq = "Flights from " + o.origin + " to " + o.destination + " on " + o.departDate +
    (o.returnDate ? " through " + o.returnDate : " one way");
  out.push({ id:"google", kind:"verify", nameZh:"喺 Google Flights 核對價錢", nameEn:"Check price on Google Flights",
    url: "https://www.google.com/travel/flights?q=" + encodeURIComponent(gq), datesPrefilled:true });

  let sky = "https://www.skyscanner.net/transport/flights/" + o.origin.toLowerCase() + "/" +
    o.destination.toLowerCase() + "/" + ymd(o.departDate) + "/";
  if (o.returnDate) sky += ymd(o.returnDate) + "/";
  out.push({ id:"skyscanner", kind:"verify", nameZh:"喺 Skyscanner 核對價錢", nameEn:"Check price on Skyscanner",
    url: sky, datesPrefilled:true });

  return out;
}

/* ================================================================
 * Provider
 * ================================================================ */

async function tpGet(env, path, params) {
  const u = new URL(TP + path);
  for (const [k,v] of Object.entries(params)) if (v != null && v !== "") u.searchParams.set(k, String(v));
  const r = await fetch(u.toString(), { headers: { "X-Access-Token": env.TRAVELPAYOUTS_TOKEN || "" } });
  const b = await r.json().catch(() => ({}));
  if (!r.ok) throw new Error("HTTP " + r.status);
  if (b.success === false) throw new Error(String(b.error || "provider error"));
  return b;
}

function makeOffer(x) {
  const rd = x.returnDate || null;
  return {
    origin:x.origin||null, destination:x.destination||null,
    departDate:x.departDate||null, returnDate:rd,
    tripType: rd ? "return" : "oneway",
    priceTotal: x.priceTotal!=null?Math.round(x.priceTotal):null,
    currency:x.currency||"HKD",
    stops:x.stops!=null?x.stops:null,
    airlineCode:x.airlineCode||null, airlineName:x.airlineName||x.airlineCode||null,
    agency:x.agency||null,
    flightNumber:x.flightNumber!=null?String(x.flightNumber):null,
    departTime:x.departTime||null, arriveTime:null,
    durationMin:x.durationMin!=null?x.durationMin:null,
    cabin:null, baggage:null,
    via: x.via || "direct_route",
    provider:"travelpayouts", isCached:true,
    fetchedAt: x.fetchedAt || new Date().toISOString(),
  };
}

async function airlineNames(env) {
  if (env.HISTORY) { const h = await env.HISTORY.get("ref:airlines","json"); if (h) return h; }
  try {
    const r = await fetch(TP + "/data/airlines.json");
    const l = await r.json(); const m = {};
    for (const a of l) if (a.code) m[a.code] = a.name;
    if (env.HISTORY) await env.HISTORY.put("ref:airlines", JSON.stringify(m), { expirationTtl: 604800 });
    return m;
  } catch (e) { return {}; }
}

async function fetchRoute(env, q, names, via) {
  const b = await tpGet(env, "/aviasales/v3/prices_for_dates", {
    origin:q.origin, destination:q.destination,
    departure_at:q.departDate, return_at:q.trip==="return"?q.returnDate:"",
    one_way:q.trip==="return"?"false":"true",
    currency:(q.currency||"hkd").toLowerCase(),
    sorting:"price", limit:20, page:1, market:q.market,
  });
  return (b.data||[]).map(d => makeOffer({
    origin:d.origin, destination:d.destination,
    departDate:(d.departure_at||"").slice(0,10),
    returnDate:(d.return_at||"").slice(0,10)||null,
    priceTotal:d.price, currency:(q.currency||"HKD").toUpperCase(),
    stops:d.transfers!=null?d.transfers:d.number_of_changes,
    airlineCode:d.airline, airlineName:names[d.airline]||d.airline,
    flightNumber:d.flight_number, durationMin:d.duration, via,
  }));
}

async function fetchMonth(env, q, names, via) {
  const b = await tpGet(env, "/v2/prices/month-matrix", {
    currency:(q.currency||"hkd").toLowerCase(), origin:q.origin, destination:q.destination,
    month:(q.departDate||"").slice(0,7)+"-01", show_to_affiliates:"true", market:q.market,
  });
  return (b.data||[]).map(d => makeOffer({
    origin:q.origin, destination:q.destination,
    departDate:d.depart_date, returnDate:d.return_date||null,
    priceTotal:d.value, currency:(q.currency||"HKD").toUpperCase(),
    stops:d.number_of_changes, airlineCode:d.gate||null,
    airlineName:names[d.gate]||d.gate||null, agency:d.gate_name||null, via,
  }));
}

async function fetchNearby(env, q, names) {
  const b = await tpGet(env, "/v2/prices/nearest-places-matrix", {
    currency:(q.currency||"hkd").toLowerCase(), origin:q.origin, destination:q.destination,
    depart_date:q.departDate, return_date:q.trip==="return"?q.returnDate:"",
    distance:q.distance||500, limit:20, flexibility:3,
    show_to_affiliates:"true", market:q.market,
  });
  return (b.prices||b.data||[]).map(d => makeOffer({
    origin:d.origin, destination:d.destination,
    departDate:d.depart_date, returnDate:d.return_date||null,
    priceTotal:d.value, currency:(q.currency||"HKD").toUpperCase(),
    stops:d.number_of_changes, airlineCode:d.gate||null,
    airlineName:names[d.gate]||d.gate||null,
    via: (d.origin!==q.origin ? "alt_origin" : (d.destination!==q.destination ? "alt_destination" : "direct_route")),
  }));
}

/* ================================================================
 * GROUND TRANSPORT — user-supplied only, never invented.
 * Stored per-user in KV. Absent entry → alternative is shown but
 * flagged as "ground cost unknown", never silently assumed zero.
 * ================================================================ */

const DEFAULT_GROUND = {};   // deliberately empty: the app knows nothing until told

async function getGround(env, uid) {
  if (!env.HISTORY) return DEFAULT_GROUND;
  return (await env.HISTORY.get("ground:" + uid, "json")) || DEFAULT_GROUND;
}

/* ================================================================
 * TRUE COST — arithmetic only. The LLM never touches this.
 * ================================================================ */

function trueCost(offer, w, ground, homeOrigin) {
  const parts = [];
  let total = offer.priceTotal;
  parts.push({ k: "fare", v: offer.priceTotal });

  let groundKnown = true;
  if (offer.origin !== homeOrigin) {
    const g = ground[offer.origin];
    if (g) {
      const c = g.costHKD * (offer.returnDate ? 2 : 1);
      const hrs = (g.minutes * (offer.returnDate ? 2 : 1)) / 60;
      total += c; parts.push({ k: "ground", v: c, detail: g.label });
      total += hrs * w.timeValue; parts.push({ k: "groundTime", v: Math.round(hrs * w.timeValue), hours: hrs });
    } else {
      groundKnown = false;
      parts.push({ k: "ground", v: null, unknown: true });
    }
  }

  if (offer.stops) {
    const p = offer.stops * w.stopPenalty;
    total += p; parts.push({ k: "stops", v: p, count: offer.stops });
  }

  const ch = offer.airlineCode && AIRLINE_SITES[offer.airlineCode] ? 0
    : agencyTier(offer.agency).tier * w.channelPremium;
  if (ch) { total += ch; parts.push({ k: "channel", v: ch }); }

  return { total: Math.round(total), parts, groundKnown };
}

function eligible(offer, w, ground, homeOrigin) {
  if (offer.stops != null && w.maxStops != null && offer.stops > w.maxStops)
    return { ok: false, why: "exceeds_max_stops" };
  if (offer.origin !== homeOrigin) {
    const g = ground[offer.origin];
    // An airport whose ground cost we do NOT know must never compete in the
    // main ranking. Otherwise ignorance looks like cheapness: an unpriced
    // transfer scores as free and unfairly beats an honestly-costed one.
    if (!g) return { ok: false, why: "ground_cost_unknown" };
    if ((g.minutes / 60) > w.maxGroundHours) return { ok: false, why: "exceeds_max_ground_time" };
  }
  return { ok: true };
}

/* ================================================================
 * OPPORTUNITY RADAR
 *
 * Answers "book or wait" from RECORDED history only.
 * It never predicts a future promotion — no data source knows when
 * an airline's next sale starts, and inventing one would be the
 * exact failure mode this product exists to avoid.
 * ================================================================ */

function percentileOf(value, arr) {
  if (!arr.length) return null;
  const below = arr.filter(x => x < value).length;
  return Math.round((below / arr.length) * 100);
}

function radar(currentPrice, history, signals) {
  const pts = (history && history.points ? history.points : []).filter(p => p.price != null);
  const prices = pts.map(p => p.price);

  const base = {
    signals: signals || [],
    signalNote: "promotion_signals_are_reports_not_forecasts",
  };

  if (prices.length < 10) {
    return { ...base,
      verdict: "insufficient_data",
      samples: prices.length, needed: 10,
      canPredict: false,
      reason: "not_enough_recorded_history",
    };
  }

  const sorted = [...prices].sort((a,b) => a-b);
  const min = sorted[0], max = sorted[sorted.length-1];
  const med = sorted[Math.floor(sorted.length/2)];
  const pct = percentileOf(currentPrice, prices);

  // Trend over the most recent third vs the oldest third
  const third = Math.max(2, Math.floor(pts.length/3));
  const early = pts.slice(0, third).map(p=>p.price);
  const late  = pts.slice(-third).map(p=>p.price);
  const avg = a => a.reduce((x,y)=>x+y,0)/a.length;
  const drift = Math.round(((avg(late) - avg(early)) / avg(early)) * 100);

  let verdict;
  if (pct <= 15) verdict = "book_now";
  else if (pct <= 35) verdict = "lean_book";
  else if (pct >= 75) verdict = "wait";
  else verdict = "neutral";

  return { ...base,
    verdict, canPredict: true,
    samples: prices.length,
    currentPrice, percentile: pct,
    lowestSeen: min, highestSeen: max, medianSeen: med,
    trendPct: drift,
    confidence: prices.length >= 45 ? "high" : prices.length >= 20 ? "medium" : "low",
    daysCovered: pts.length ? (pts[0].date + " → " + pts[pts.length-1].date) : null,
  };
}

/* ================================================================
 * AGENT PLANNER
 * Produces an explicit plan, executes it, and records for EVERY step
 * whether it ran, what it found, and — if it did not run — WHY NOT.
 * ================================================================ */

function buildPlan(q, caps) {
  const steps = [
    { id:"direct", zh:"搜尋 " + q.origin + " → " + q.destination + " 指定日期",
      en:"Search " + q.origin + " → " + q.destination + " on your dates", runnable:true },
    { id:"dates", zh:"檢查前後日期(整月)", en:"Check flexible dates (whole month)", runnable:true },
    { id:"nearby", zh:"檢查附近出發同到達機場", en:"Check nearby departure & arrival airports", runnable:true },
    { id:"history", zh:"對比你自己記錄嘅歷史價", en:"Compare against your recorded price history",
      runnable: caps.hasHistory, skipReason: caps.hasHistory ? null : "no_kv_history_binding" },
    { id:"promos", zh:"掃描社群優惠情報", en:"Scan community promotion signals", runnable:true },
    { id:"airline_direct", zh:"查航空公司官網即時票價", en:"Fetch airline official website prices",
      runnable:false, skipReason:"no_airline_api_access" },
    { id:"ota", zh:"查 Trip.com / Expedia 即時票價", en:"Fetch Trip.com / Expedia live prices",
      runnable:false, skipReason:"no_ota_api_access" },
    { id:"rank", zh:"用你嘅出行取向排序", en:"Rank by your traveller profile", runnable:true },
  ];
  return steps;
}

/**
 * WHY NOT — permanent structural gaps, always disclosed.
 */
const WHY_NOT = {
  no_airline_api_access: {
    zh: "航空公司官網冇公開 API,個 App 攞唔到官網即時票價。下面有官網連結俾你自己核對。",
    en: "Airline websites expose no public API, so official-site prices cannot be fetched. Use the airline link to check yourself.",
  },
  no_ota_api_access: {
    zh: "Trip.com / Expedia 冇公開 API(要商業合作),所以冇辦法直接比價。",
    en: "Trip.com and Expedia have no public API (partnership required), so their prices cannot be compared directly.",
  },
  no_kv_history_binding: {
    zh: "未接 KV 儲存,所以未有你自己嘅歷史價紀錄。",
    en: "No KV storage bound, so no personal price history has been recorded yet.",
  },
  carrier_not_enumerable: {
    zh: "呢個資料來源只回傳每條航線最平嘅報價,唔會列出所有航空公司,所以無法確認某間航空公司有冇航班。",
    en: "This source returns only the cheapest quote per route, not every carrier, so the absence of a specific airline cannot be confirmed.",
  },
  provider_error: { zh: "資料來源今次回應失敗。", en: "The data source failed to respond for this step." },
  no_results: { zh: "呢一步搵唔到任何快取票價。", en: "This step returned no cached fares." },
};

/* ================================================================
 * ORCHESTRATION
 * ================================================================ */

const json = (o,s=200) => new Response(JSON.stringify(o), {
  status:s, headers:{ "Content-Type":"application/json", "Cache-Control":"no-store" }});

async function handleOrchestrate(request, env) {
  const t0 = Date.now();
  const p = new URL(request.url).searchParams;
  const uid = p.get("uid") || "anon";
  const q = {
    origin:(p.get("origin")||"").toUpperCase().trim(),
    destination:(p.get("destination")||"").toUpperCase().trim(),
    departDate:p.get("departDate")||"",
    returnDate:p.get("returnDate")||"",
    trip: p.get("trip")==="oneway" ? "oneway" : "return",
    currency:(p.get("currency")||"HKD").toUpperCase(),
    pax: parseInt(p.get("pax")||"1",10),
    distance: parseInt(p.get("distance")||"500",10),
    market: env.DEFAULT_MARKET || "hk",
  };

  if (!env.TRAVELPAYOUTS_TOKEN) return json({ error:"TRAVELPAYOUTS_TOKEN not configured" },500);
  if (!q.origin || !q.destination) return json({ error:"origin and destination required" },400);
  if (!q.departDate) return json({ error:"departDate required" },400);

  // weights: stored quiz answers > profile > balanced
  let weights = PROFILES[p.get("profile")] || PROFILES.balanced;
  let answers = {};
  if (env.HISTORY) {
    const saved = await env.HISTORY.get("prefs:"+uid, "json");
    if (saved) { answers = saved.answers || {}; weights = weightsFromAnswers(answers, PROFILES[saved.profile] || weights); }
  }
  if (p.get("profile") && !Object.keys(answers).length) weights = { ...PROFILES[p.get("profile")], derivedFrom:"profile", bounds:null };

  const caps = { hasHistory: !!env.HISTORY };
  const plan = buildPlan(q, caps);
  const names = await airlineNames(env);
  const ground = await getGround(env, uid);

  const log = [];
  const record = (id, status, extra) => {
    const s = plan.find(x=>x.id===id) || { id };
    log.push({ id, zh:s.zh, en:s.en, status, ...extra });
  };

  let all = [];

  // --- step: direct
  try {
    const r = await fetchRoute(env, q, names, "direct_route");
    all = all.concat(r);
    record("direct", r.length ? "ok" : "empty", { found:r.length, whyNot: r.length?null:"no_results" });
  } catch(e) { record("direct","failed",{ found:0, whyNot:"provider_error", detail:e.message }); }

  // --- step: flexible dates
  try {
    const r = await fetchMonth(env, q, names, "alt_date");
    all = all.concat(r);
    record("dates", r.length ? "ok" : "empty", { found:r.length, whyNot: r.length?null:"no_results" });
  } catch(e) { record("dates","failed",{ found:0, whyNot:"provider_error", detail:e.message }); }

  // --- step: nearby airports
  try {
    const r = await fetchNearby(env, q, names);
    all = all.concat(r);
    const alt = r.filter(o=>o.via!=="direct_route").length;
    record("nearby", r.length ? "ok" : "empty", { found:alt, whyNot: r.length?null:"no_results" });
  } catch(e) { record("nearby","failed",{ found:0, whyNot:"provider_error", detail:e.message }); }

  // dedupe
  const seen = new Set(); const offers = [];
  for (const o of all) {
    if (o.priceTotal==null || o.priceTotal<=0) continue;
    if (o.tripType !== q.trip) continue;
    const k = [o.origin,o.destination,o.departDate,o.returnDate,o.priceTotal,o.airlineCode].join("|");
    if (seen.has(k)) continue;
    seen.add(k); offers.push(o);
  }

  // --- step: history + radar
  let history = null, rad = null;
  const routeKey = q.origin + "-" + q.destination;
  if (env.HISTORY) {
    history = await env.HISTORY.get("hist:"+routeKey, "json");
    record("history", history ? "ok" : "empty",
      { found: history && history.points ? history.points.length : 0,
        whyNot: history ? null : "no_results" });
  } else {
    record("history","skipped",{ found:0, whyNot:"no_kv_history_binding" });
  }

  // --- step: promo signals
  let signals = [];
  try {
    signals = await promoSignals(env, q, names);
    record("promos", signals.length ? "ok" : "empty", { found:signals.length, whyNot: signals.length?null:"no_results" });
  } catch(e) { record("promos","failed",{ found:0, whyNot:"provider_error", detail:e.message }); }

  // --- structurally impossible steps
  record("airline_direct","skipped",{ found:0, whyNot:"no_airline_api_access" });
  record("ota","skipped",{ found:0, whyNot:"no_ota_api_access" });

  // --- step: rank by true cost
  const scored = offers.map(o => {
    const el = eligible(o, weights, ground, q.origin);
    const tc = trueCost(o, weights, ground, q.origin);
    return { ...o, trueCost: tc.total, costParts: tc.parts, groundKnown: tc.groundKnown,
      eligible: el.ok, ineligibleWhy: el.why || null,
      channels: channels(o, env.TP_MARKER, q.pax) };
  });
  const ranked = scored.filter(o=>o.eligible).sort((a,b)=>a.trueCost-b.trueCost);
  const needsInput = scored.filter(o=>!o.eligible && o.ineligibleWhy==="ground_cost_unknown")
    .sort((a,b)=>a.priceTotal-b.priceTotal);
  const excluded = scored.filter(o=>!o.eligible && o.ineligibleWhy!=="ground_cost_unknown");
  record("rank","ok",{ found:ranked.length });

  // radar uses the cheapest ELIGIBLE fare on the requested route pair
  const onRoute = ranked.filter(o => o.origin===q.origin && o.destination===q.destination);
  if (onRoute.length) rad = radar(onRoute[0].priceTotal, history, signals);
  else if (ranked.length) rad = radar(ranked[0].priceTotal, history, signals);

  // record today's cheapest for tomorrow's radar
  if (env.HISTORY && onRoute.length) {
    try {
      const h = history || { route:routeKey, points:[] };
      const date = new Date().toISOString().slice(0,10);
      h.points = h.points.filter(x => !(x.date===date && x.tripType===q.trip));
      h.points.push({ date, price:onRoute[0].priceTotal, currency:onRoute[0].currency, tripType:q.trip });
      h.points.sort((a,b)=>a.date.localeCompare(b.date));
      if (h.points.length>180) h.points = h.points.slice(-180);
      await env.HISTORY.put("hist:"+routeKey, JSON.stringify(h));
    } catch(e) {}
  }

  // --- confidence: three separate numbers, never blended
  const ran = log.filter(s=>s.status==="ok").length;
  const planned = plan.filter(s=>s.runnable).length;
  const confidence = {
    price: { level: "cached", note: "cached_48h", live: false },
    completeness: {
      ranSteps: ran, plannedSteps: planned,
      pct: planned ? Math.round((ran/planned)*100) : 0,
      unreachable: log.filter(s=>s.status==="skipped").map(s=>s.whyNot),
    },
    timing: rad && rad.canPredict
      ? { level: rad.confidence, samples: rad.samples }
      : { level: "none", samples: rad ? rad.samples : 0, note: "insufficient_history" },
  };

  // --- work saved (the north-star metric)
  const sitesCovered = [];
  if (log.find(s=>s.id==="direct"&&s.status==="ok")) sitesCovered.push("aviasales_cache");
  if (log.find(s=>s.id==="nearby"&&s.status==="ok")) sitesCovered.push("nearby_airport_lookup");
  if (log.find(s=>s.id==="dates"&&s.status==="ok")) sitesCovered.push("date_calendar");
  if (log.find(s=>s.id==="history"&&s.status==="ok")) sitesCovered.push("price_history");
  if (log.find(s=>s.id==="promos"&&s.status==="ok")) sitesCovered.push("deal_communities");
  const workSaved = {
    checksRun: sitesCovered.length,
    manualEquivalent: sitesCovered.length * 4,   // ~4 min per lookup done by hand
    elapsedMs: Date.now()-t0,
    stillWorthChecking: ["airline_official_site", "one_major_ota"],
  };
  if (env.HISTORY) {
    try {
      const m = (await env.HISTORY.get("metrics:"+uid,"json")) || { searches:0, minutesSaved:0 };
      m.searches += 1; m.minutesSaved += workSaved.manualEquivalent;
      await env.HISTORY.put("metrics:"+uid, JSON.stringify(m));
      workSaved.lifetime = m;
    } catch(e) {}
  }

  return json({
    query:q, weights, plan, log,
    offers: ranked.slice(0,40), needsInput: needsInput.slice(0,8), excluded: excluded.slice(0,10),
    radar: rad, confidence, workSaved,
    whyNot: WHY_NOT,
    groundKnownFor: Object.keys(ground),
  });
}

/* ================================================================
 * Promotion signals — reports, never forecasts
 * ================================================================ */

const DEAL_WORDS = ["error fare","mistake fare","flash sale","promo","promotion","sale","deal","discount","% off","fare drop"];

async function promoSignals(env, q, names) {
  const key = "signals:v2";
  if (env.HISTORY) { const c = await env.HISTORY.get(key,"json"); if (c) return filterSignals(c, q, names); }
  const subs = ["TravelDeals","awardtravel","flights"];
  const out = [];
  await Promise.all(subs.map(async s => {
    try {
      const r = await fetch("https://www.reddit.com/r/"+s+"/new.json?limit=25",
        { headers:{ "User-Agent":"flight-orchestrator/1.0 (personal)" }});
      if (!r.ok) return;
      const d = await r.json();
      for (const c of (d.data&&d.data.children)||[]) {
        out.push({ source:"r/"+s, title:c.data.title,
          url:"https://reddit.com"+c.data.permalink, ts:c.data.created_utc*1000 });
      }
    } catch(e) {}
  }));
  if (env.HISTORY) await env.HISTORY.put(key, JSON.stringify(out), { expirationTtl: 10800 });
  return filterSignals(out, q, names);
}

function filterSignals(list, q, names) {
  const dest = (q.destination||"").toLowerCase();
  const org = (q.origin||"").toLowerCase();
  const fp = s => s.toLowerCase().replace(/[^a-z0-9 ]/g,"").replace(/\s+/g," ").trim().slice(0,70);
  const seen = new Map();
  for (const x of list) {
    const t = x.title.toLowerCase();
    let score = 0;
    for (const w of DEAL_WORDS) if (t.includes(w)) score += 2;
    if (t.includes("error fare")||t.includes("mistake fare")) score += 5;
    if (dest && t.includes(dest)) score += 5;
    if (org && t.includes(org)) score += 4;
    if (score < 5) continue;
    const k = fp(x.title);
    const prev = seen.get(k);
    if (!prev) seen.set(k, { ...x, score, alsoSeenIn: [] });
    else if (prev.source !== x.source && !prev.alsoSeenIn.includes(x.source)) {
      prev.alsoSeenIn.push(x.source); prev.score += 1;
    }
  }
  return [...seen.values()].sort((a,b)=>b.score-a.score||b.ts-a.ts).slice(0,8);
}

/* ================================================================
 * Preferences
 * ================================================================ */

async function handlePrefs(request, env) {
  const u = new URL(request.url);
  const uid = u.searchParams.get("uid") || "anon";
  if (request.method === "GET") {
    const saved = env.HISTORY ? await env.HISTORY.get("prefs:"+uid,"json") : null;
    const answers = (saved && saved.answers) || {};
    return json({ quiz: QUIZ, profiles: Object.keys(PROFILES), saved,
      weights: weightsFromAnswers(answers, PROFILES[(saved&&saved.profile)||"balanced"]) });
  }
  const body = await request.json().catch(()=>({}));
  const rec = { profile: body.profile || "balanced", answers: body.answers || {}, savedAt: new Date().toISOString() };
  if (env.HISTORY) await env.HISTORY.put("prefs:"+uid, JSON.stringify(rec));
  return json({ ok:true, saved:rec, weights: weightsFromAnswers(rec.answers, PROFILES[rec.profile]) });
}

async function handleGround(request, env) {
  const u = new URL(request.url);
  const uid = u.searchParams.get("uid") || "anon";
  if (request.method === "GET") return json({ ground: await getGround(env, uid) });
  const body = await request.json().catch(()=>({}));
  const cur = await getGround(env, uid);
  if (body.code) {
    if (body.remove) delete cur[body.code.toUpperCase()];
    else cur[body.code.toUpperCase()] = {
      costHKD: Math.max(0, parseInt(body.costHKD||0,10)),
      minutes: Math.max(0, parseInt(body.minutes||0,10)),
      label: (body.label||"").slice(0,60),
    };
  }
  if (env.HISTORY) await env.HISTORY.put("ground:"+uid, JSON.stringify(cur));
  return json({ ok:true, ground:cur });
}

/* ================================================================
 * Narration — Gemini renders arithmetic it did not perform
 * ================================================================ */

async function handleExplain(request, env) {
  const b = await request.json().catch(()=>({}));
  const { best, radar: rad, confidence, lang, weights } = b;
  const zh = lang === "zh";

  let fb;
  if (!best) fb = zh ? "今次搵唔到合適選擇。" : "No suitable option found.";
  else {
    const p = best.costParts || [];
    const bits = p.map(x => x.k + (x.v!=null ? " " + x.v : " (unknown)")).join(", ");
    fb = (zh ? "最抵:" : "Best: ") + best.origin + "→" + best.destination + " " +
      best.currency + best.priceTotal + (zh ? ",真實成本 " : ", true cost ") + best.trueCost +
      " (" + bits + ")." +
      (rad && rad.canPredict ? (zh ? " 現價喺你記錄嘅第 " + rad.percentile + " 百分位。" :
        " Currently at the " + rad.percentile + "th percentile of your recorded history.") : "");
  }

  if (!env.GEMINI_API_KEY) return json({ text: fb, source:"rules" });
  try {
    const facts = { best: best ? {
        origin:best.origin, destination:best.destination, price:best.priceTotal,
        currency:best.currency, trueCost:best.trueCost, costParts:best.costParts,
        stops:best.stops, airline:best.airlineName, via:best.via,
        departDate:best.departDate, returnDate:best.returnDate,
        groundKnown:best.groundKnown } : null,
      radar: rad, confidence, weights };
    const prompt =
      "You are a travel decision assistant. Use ONLY the numbers in this JSON. " +
      "Never invent or adjust a price. Never predict a future promotion or sale — " +
      "if radar.canPredict is false, say there is not enough recorded history to judge timing. " +
      "Never claim to have searched any website not listed. " +
      "If groundKnown is false, say the ground transport cost for that airport is unknown and must be added by the traveller. " +
      (zh ? "用香港廣東話書面語回答,120 字以內,純文字。" : "Reply in English, under 110 words, plain text. ") +
      "Explain which option wins and why, using the cost breakdown. State book-or-wait only from radar. JSON: " +
      JSON.stringify(facts);
    const r = await fetch("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key="+env.GEMINI_API_KEY,
      { method:"POST", headers:{ "Content-Type":"application/json" },
        body: JSON.stringify({ contents:[{ parts:[{ text:prompt }]}],
          generationConfig:{ maxOutputTokens:320, temperature:0.3 }})});
    const j = await r.json();
    if (!r.ok) throw new Error((j.error&&j.error.message)||"HTTP "+r.status);
    const txt = j.candidates&&j.candidates[0]&&j.candidates[0].content&&
      j.candidates[0].content.parts&&j.candidates[0].content.parts[0]&&j.candidates[0].content.parts[0].text;
    return json({ text:(txt&&txt.trim())||fb, source:"gemini" });
  } catch(e) { return json({ text:fb, source:"rules", error:e.message }); }
}

async function handlePlaces(request) {
  const term = new URL(request.url).searchParams.get("q")||"";
  if (term.length<2) return json({ places:[] });
  try {
    const r = await fetch("https://autocomplete.travelpayouts.com/places2?locale=en&types[]=city&types[]=airport&term="+encodeURIComponent(term));
    const l = await r.json();
    return json({ places:(l||[]).slice(0,8).map(x=>({ code:x.code, name:x.name, country:x.country_name })) });
  } catch(e) { return json({ places:[], error:e.message }); }
}

export default {
  async fetch(request, env) {
    const p = new URL(request.url).pathname;
    try {
      if (p==="/api/orchestrate") return await handleOrchestrate(request, env);
      if (p==="/api/prefs") return await handlePrefs(request, env);
      if (p==="/api/ground") return await handleGround(request, env);
      if (p==="/api/explain" && request.method==="POST") return await handleExplain(request, env);
      if (p==="/api/places") return await handlePlaces(request);
      if (p==="/manifest.json") return new Response(JSON.stringify({
        name:"Flight Deal Orchestrator", short_name:"Orchestrator", start_url:"/",
        display:"standalone", background_color:"#0d1117", theme_color:"#0d1117", icons:[] }),
        { headers:{ "Content-Type":"application/json" }});
      if (p==="/sw.js") return new Response(SW, { headers:{ "Content-Type":"application/javascript" }});
      return new Response(HTML, { headers:{ "Content-Type":"text/html;charset=utf-8" }});
    } catch(e) { return json({ error:e.message },500); }
  },
};

const SW = [
 "self.addEventListener('install',function(e){self.skipWaiting()});",
 "self.addEventListener('activate',function(e){e.waitUntil(self.clients.claim())});",
 "self.addEventListener('fetch',function(e){",
 " if(e.request.method!=='GET')return;",
 " if(new URL(e.request.url).pathname.indexOf('/api/')===0)return;",
 " e.respondWith(fetch(e.request).catch(function(){return caches.match(e.request)}))});",
].join("\n");

/* ================================================================
 * UI
 * ================================================================ */

const HTML = `<!DOCTYPE html>
<html lang="zh-Hant"><head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#0d1117">
<meta name="apple-mobile-web-app-capable" content="yes">
<link rel="manifest" href="/manifest.json">
<title>Flight Deal Orchestrator</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Noto+Sans+TC:wght@400;500;700&display=swap" rel="stylesheet">
<style>
:root{--bg:#0d1117;--card:#161b22;--card2:#1c2330;--line:#262d3a;--tx:#e6edf3;--dim:#8b949e;
--acc:#3fb950;--acc2:#2ea043;--hot:#f85149;--warm:#d29922;--cool:#58a6ff;--vio:#a371f7;
--f:'Inter','Noto Sans TC',system-ui,-apple-system,sans-serif}
*{box-sizing:border-box;margin:0;padding:0;-webkit-tap-highlight-color:transparent}
body{background:var(--bg);color:var(--tx);font-family:var(--f);font-size:15px;line-height:1.5;min-height:100vh}
.wrap{max-width:980px;margin:0 auto;padding:14px 14px 80px}
header{display:flex;align-items:center;justify-content:space-between;padding:6px 0 12px;gap:10px}
.logo{font-weight:700;font-size:1rem}.logo span{color:var(--acc)}
.lang{display:flex;border:1px solid var(--line);border-radius:8px;overflow:hidden}
.lang button{background:none;border:none;color:var(--dim);padding:6px 11px;font-size:.78rem;cursor:pointer;font-family:var(--f)}
.lang button.on{background:var(--card2);color:var(--tx);font-weight:600}
.tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-bottom:12px}
.tabs button{background:var(--card);border:1px solid var(--line);color:var(--dim);border-radius:9px;padding:10px 4px;font-size:.78rem;cursor:pointer;font-family:var(--f)}
.tabs button.on{border-color:var(--acc);color:var(--acc);background:var(--card2)}
.panel{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:14px;margin-bottom:10px}
.row{display:grid;gap:10px;margin-bottom:10px}.r2{grid-template-columns:1fr 1fr}.r3{grid-template-columns:1fr 1fr 1fr}
label{display:block;font-size:.7rem;color:var(--dim);margin-bottom:5px}
input,select{width:100%;background:var(--bg);border:1px solid var(--line);border-radius:8px;color:var(--tx);padding:11px 10px;font-size:16px;font-family:var(--f);appearance:none}
input:focus,select:focus{outline:none;border-color:var(--acc)}
.trip{display:flex;gap:6px;margin-bottom:10px}
.trip button,.profs button{flex:1;background:var(--card);border:1px solid var(--line);color:var(--dim);border-radius:9px;padding:9px 4px;font-size:.76rem;cursor:pointer;font-family:var(--f)}
.trip button.on,.profs button.on{border-color:var(--acc);color:var(--acc);background:var(--card2)}
.profs{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-bottom:10px}
button.go{width:100%;background:var(--acc);color:#04260d;border:none;border-radius:9px;padding:14px;font-size:.95rem;font-weight:700;cursor:pointer;font-family:var(--f)}
button.go:disabled{opacity:.5}
button.sec{width:100%;background:none;color:var(--cool);border:1px solid var(--line);border-radius:9px;padding:11px;font-size:.82rem;cursor:pointer;font-family:var(--f);margin-top:8px}
.eyebrow{font-size:.66rem;color:var(--dim);letter-spacing:.16em;text-transform:uppercase;margin:18px 0 8px}
/* agent log */
.step{display:flex;gap:10px;align-items:flex-start;padding:9px 12px;background:var(--card);border:1px solid var(--line);border-radius:9px;margin-bottom:5px;font-size:.82rem}
.step .ic{width:18px;flex-shrink:0;text-align:center;font-weight:700}
.step.ok .ic{color:var(--acc)}.step.empty .ic{color:var(--warm)}
.step.skipped .ic{color:var(--dim)}.step.failed .ic{color:var(--hot)}
.step .why{font-size:.73rem;color:var(--dim);margin-top:3px;line-height:1.5}
.step .cnt{margin-left:auto;font-size:.72rem;color:var(--dim);white-space:nowrap;padding-left:8px}
/* radar */
.radar{background:var(--card2);border:1px solid var(--line);border-radius:12px;padding:14px;margin-bottom:10px}
.rv{font-size:1.1rem;font-weight:700;margin-bottom:4px}
.rv.book_now{color:var(--acc)}.rv.lean_book{color:var(--cool)}
.rv.wait{color:var(--warm)}.rv.neutral{color:var(--dim)}.rv.insufficient_data{color:var(--dim)}
.bar{height:8px;background:var(--bg);border-radius:5px;position:relative;margin:12px 0 6px;overflow:hidden}
.bar .fill{position:absolute;top:0;bottom:0;left:0;background:linear-gradient(90deg,var(--acc),var(--warm),var(--hot))}
.bar .mk{position:absolute;top:-3px;width:3px;height:14px;background:var(--tx);border-radius:2px}
.rmeta{font-size:.72rem;color:var(--dim);display:flex;gap:12px;flex-wrap:wrap;margin-top:8px}
/* confidence */
.conf{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:10px}
.cbox{background:var(--card);border:1px solid var(--line);border-radius:9px;padding:10px}
.cbox .k{font-size:.64rem;color:var(--dim);text-transform:uppercase;letter-spacing:.1em}
.cbox .v{font-size:.9rem;font-weight:700;margin-top:4px}
.cbox .s{font-size:.68rem;color:var(--dim);margin-top:2px}
/* offers */
.card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:13px;margin-bottom:9px}
.card.best{border-color:var(--acc);border-width:2px}
.ctop{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}
.route{font-weight:700;font-size:1rem}.route .ar{color:var(--dim);font-weight:400;margin:0 5px}
.meta{font-size:.76rem;color:var(--dim);margin-top:4px;display:flex;gap:8px;flex-wrap:wrap}
.tag{font-size:.64rem;border-radius:5px;padding:2px 7px;font-weight:600}
.tag-alt_origin{background:#2b2313;color:#d29922}.tag-alt_destination{background:#1a2733;color:#58a6ff}
.tag-alt_date{background:#221a33;color:#a371f7}.tag-direct_route{background:#0f2f1a;color:#3fb950}
.price{text-align:right;white-space:nowrap}
.price .p{font-size:1.2rem;font-weight:700}
.price .tc{font-size:.7rem;color:var(--dim);margin-top:2px}
.work{margin-top:10px;padding-top:10px;border-top:1px dashed var(--line);font-size:.73rem;color:var(--dim);font-family:ui-monospace,monospace;line-height:1.8}
.work .pos{color:var(--acc)}.work .neg{color:var(--warm)}
.work .unk{color:var(--hot)}
.ch{margin-top:11px;padding-top:10px;border-top:1px solid var(--line)}
.chl{font-size:.64rem;color:var(--dim);margin-bottom:7px}
.chw{display:flex;gap:6px;flex-wrap:wrap}
.b{text-decoration:none;border-radius:7px;padding:8px 13px;font-size:.76rem;font-weight:600;border:1px solid var(--line);color:var(--dim);background:var(--bg);display:inline-block}
.b.book{background:var(--acc);color:#04260d;border-color:var(--acc)}
.b.cmp{border-color:#33405c;color:var(--cool)}
.b.dis{opacity:.55}
.note{background:var(--card2);border:1px solid var(--line);border-left:3px solid var(--warm);border-radius:0 8px 8px 0;padding:11px 13px;font-size:.77rem;color:var(--dim);line-height:1.65;margin:10px 0}
.ai{background:linear-gradient(180deg,#1a1430,#161b22);border:1px solid #2f2450;border-left:3px solid var(--vio);border-radius:0 10px 10px 0;padding:13px;margin:10px 0;font-size:.88rem;line-height:1.65}
.ai .l{font-size:.64rem;color:var(--vio);letter-spacing:.1em;text-transform:uppercase;font-weight:700;margin-bottom:6px}
.saved{background:#0f2f1a;border:1px solid #1d5c31;border-radius:10px;padding:12px;margin-bottom:10px;font-size:.82rem}
.saved b{color:var(--acc)}
.q{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:13px;margin-bottom:8px}
.qt{font-size:.9rem;margin-bottom:9px}
.qb{display:flex;gap:8px}
.qb button{flex:1;background:var(--bg);border:1px solid var(--line);color:var(--dim);border-radius:8px;padding:10px;font-size:.82rem;cursor:pointer;font-family:var(--f)}
.qb button.on{border-color:var(--acc);color:var(--acc);background:var(--card2);font-weight:600}
.sig{background:var(--card);border:1px solid var(--line);border-radius:9px;padding:10px 12px;margin-bottom:6px}
.sig a{color:var(--tx);text-decoration:none;font-size:.84rem;line-height:1.4}
.sig .m{font-size:.66rem;color:var(--dim);margin-top:5px}
.status{font-size:.82rem;color:var(--warm);margin:10px 2px;min-height:1.2em}
.status.err{color:var(--hot)}
.empty{text-align:center;padding:34px 18px;color:var(--dim);font-size:.86rem}
.hidden{display:none}
footer{margin-top:26px;padding-top:12px;border-top:1px solid var(--line);font-size:.68rem;color:var(--dim);line-height:1.7}
@media(max-width:560px){.r3,.conf{grid-template-columns:1fr}.profs{grid-template-columns:repeat(2,1fr)}.ctop{flex-direction:column}.price{text-align:left}}
</style></head><body>
<div class="wrap">
<header><div class="logo">Flight<span>Deal</span> Orchestrator</div>
<div class="lang"><button id="lz" class="on">繁中</button><button id="le">EN</button></div></header>

<div class="tabs">
  <button class="on" data-tab="go" data-i="tab_go">搵最佳方案</button>
  <button data-tab="me" data-i="tab_me">我嘅取向</button>
  <button data-tab="sig" data-i="tab_sig">優惠情報</button>
</div>

<section id="t-go">
  <div class="trip">
    <button class="on" data-trip="return" data-i="t_ret">來回</button>
    <button data-trip="oneway" data-i="t_one">單程</button>
  </div>
  <div class="panel">
    <div class="row r2">
      <div><label data-i="from">出發地</label><input id="origin" placeholder="HKG" autocomplete="off"></div>
      <div><label data-i="to">目的地</label><input id="dest" placeholder="KTM" autocomplete="off"></div>
    </div>
    <div class="row r2">
      <div><label data-i="dep">去程</label><input id="dep" type="date"></div>
      <div id="retW"><label data-i="ret">回程</label><input id="ret" type="date"></div>
    </div>
    <div class="row r3">
      <div><label data-i="cur">貨幣</label><select id="cur"><option>HKD</option><option>USD</option><option>TWD</option><option>SGD</option><option>JPY</option><option>EUR</option><option>GBP</option></select></div>
      <div><label data-i="pax">人數</label><select id="pax"><option>1</option><option>2</option><option>3</option><option>4</option></select></div>
      <div><label data-i="rad">附近機場半徑</label><select id="dist"><option value="200">200 km</option><option value="500" selected>500 km</option><option value="1000">1000 km</option></select></div>
    </div>
    <button class="go" id="go" data-i="run">開始研究</button>
  </div>
  <div class="status" id="status"></div>
  <div id="out"></div>
</section>

<section id="t-me" class="hidden">
  <div class="eyebrow" data-i="e_prof">出行類型</div>
  <div class="profs">
    <button data-p="backpacker" data-i="p_back">背包客</button>
    <button data-p="balanced" class="on" data-i="p_bal">平衡</button>
    <button data-p="family" data-i="p_fam">家庭</button>
    <button data-p="business" data-i="p_biz">公幹</button>
  </div>
  <div class="eyebrow" data-i="e_quiz">幾條問題,幫你調校</div>
  <div id="quiz"></div>
  <div class="panel" id="wbox"></div>
  <div class="eyebrow" data-i="e_ground">你自己嘅陸路交通成本</div>
  <div class="note" data-i="n_ground"></div>
  <div class="panel">
    <div class="row r3">
      <div><label data-i="g_code">機場代碼</label><input id="g-code" placeholder="SZX" maxlength="3"></div>
      <div><label data-i="g_cost">單程車費</label><input id="g-cost" type="number" placeholder="95"></div>
      <div><label data-i="g_min">單程分鐘</label><input id="g-min" type="number" placeholder="150"></div>
    </div>
    <button class="sec" id="g-add" data-i="g_add">加入</button>
    <div id="g-list" style="margin-top:10px"></div>
  </div>
</section>

<section id="t-sig" class="hidden"><div id="sigout" class="empty" data-i="sig_hint">做一次搜尋之後,呢度會顯示相關嘅社群優惠情報。</div></section>

<footer><span data-i="foot"></span></footer>
</div>
<script>
(function(){
var $=function(i){return document.getElementById(i)};
var UID=(function(){try{var k=localStorage.getItem('fdo_uid');if(!k){k='u'+Math.random().toString(36).slice(2,10);localStorage.setItem('fdo_uid',k)}return k}catch(e){return 'anon'}})();

var I={zh:{
 tab_go:'搵最佳方案',tab_me:'我嘅取向',tab_sig:'優惠情報',
 t_ret:'來回',t_one:'單程',from:'出發地',to:'目的地',dep:'去程',ret:'回程',
 cur:'貨幣',pax:'人數',rad:'附近機場半徑',run:'開始研究',
 e_prof:'出行類型',e_quiz:'幾條問題,幫你調校',e_ground:'你自己嘅陸路交通成本',
 p_back:'背包客',p_bal:'平衡',p_fam:'家庭',p_biz:'公幹',
 n_ground:'呢個系統唔會估你去另一個機場要幾錢。你自己填一次,佢先會計入「真實成本」。冇填嘅機場會標示為「未知」,唔會當零計。',
 g_code:'機場代碼',g_cost:'單程車費 (HKD)',g_min:'單程分鐘',g_add:'加入',
 sig_hint:'做一次搜尋之後,呢度會顯示相關嘅社群優惠情報。',
 researching:'研究緊…',yes:'肯',no:'唔肯',
 e_plan:'AI 做咗咩',e_conf:'信心',e_radar:'買定等?',e_best:'建議',e_all:'所有選擇',e_ex:'已排除',
 e_need:'要你補資料先排得到',n_need:'呢啲機場可能更平,但個系統唔知你去嗰度要幾錢幾耐,所以唔會當免費計入排名。去「我嘅取向」填一次就得。',
 c_price:'價錢',c_comp:'完整度',c_time:'時機',
 c_cached:'快取價',c_cached_s:'過去 48 小時搜尋紀錄',
 c_steps:'{a}/{b} 步完成',c_none:'歷史不足',c_samples:'{n} 日紀錄',
 v_book_now:'🔥 而家買',v_lean_book:'⭐ 偏向買',v_wait:'⏳ 建議等',v_neutral:'⚖️ 普通',v_insufficient_data:'📊 資料未夠',
 r_pct:'現價喺你紀錄嘅第 {n} 百分位',
 r_none:'只錄咗 {n} 日(要 {m} 日先講得準)。呢個系統唔會靠估。',
 r_range:'最低 {lo} · 中位 {med} · 最高 {hi}',
 r_trend:'近期趨勢 {n}%',
 r_sig:'⚠️ 下面嘅係社群報料,唔係預測。冇任何資料來源知道航空公司下次幾時減價。',
 w_saved:'今次幫你查咗 <b>{n}</b> 樣嘢,慳返大約 <b>{m}</b> 分鐘手動比價。',
 w_still:'仍然建議你自己核對:航空公司官網、一間大型 OTA。',
 fare:'機票',ground:'陸路交通',groundTime:'交通時間',stops:'轉機',channel:'渠道風險',
 tc:'真實成本',unknown:'未知',
 ch_book:'訂票',ch_cmp:'比較 / 核對',
 ag_only:'(呢個代理由資料來源提供,冇直接連結)',
 no_res:'搵唔到合適選擇。試下改日期或者放寬條件。',
 ex_stops:'轉機太多',ex_ground:'陸路交通時間超出你嘅上限',ex_unknown:'未知陸路交通成本',
 foot:'票價來自 Aviasales 快取,唔係即時報價。呢個系統只幫你決定,唔會幫你落單。'
},en:{
 tab_go:'Find best plan',tab_me:'My priorities',tab_sig:'Deal signals',
 t_ret:'Round trip',t_one:'One way',from:'From',to:'To',dep:'Depart',ret:'Return',
 cur:'Currency',pax:'Travellers',rad:'Nearby radius',run:'Start research',
 e_prof:'Traveller type',e_quiz:'A few questions to tune this',e_ground:'Your own ground transport costs',
 p_back:'Backpacker',p_bal:'Balanced',p_fam:'Family',p_biz:'Business',
 n_ground:'This system will not guess what it costs you to reach another airport. Enter it once and it becomes part of true cost. Airports you have not entered are marked unknown, never assumed to be free.',
 g_code:'Airport code',g_cost:'One-way cost (HKD)',g_min:'One-way minutes',g_add:'Add',
 sig_hint:'Run a search and relevant community deal signals will appear here.',
 researching:'Researching…',yes:'Yes',no:'No',
 e_plan:'What the AI did',e_conf:'Confidence',e_radar:'Book or wait?',e_best:'Recommendation',e_all:'All options',e_ex:'Excluded',
 e_need:'Needs your input before ranking',n_need:'These airports may be cheaper, but the system does not know what the transfer costs you in money or time, so it will not rank them as if it were free. Enter it once under My priorities.',
 c_price:'Price',c_comp:'Completeness',c_time:'Timing',
 c_cached:'Cached',c_cached_s:'from searches in last 48h',
 c_steps:'{a}/{b} steps done',c_none:'No history',c_samples:'{n} days recorded',
 v_book_now:'🔥 Book now',v_lean_book:'⭐ Lean book',v_wait:'⏳ Wait',v_neutral:'⚖️ Neutral',v_insufficient_data:'📊 Not enough data',
 r_pct:'Currently at the {n}th percentile of your recorded history',
 r_none:'Only {n} days recorded ({m} needed). This system will not guess.',
 r_range:'Low {lo} · Median {med} · High {hi}',
 r_trend:'Recent trend {n}%',
 r_sig:'⚠️ Below are community reports, not forecasts. No data source knows when an airline will next hold a sale.',
 w_saved:'Checked <b>{n}</b> things for you, saving roughly <b>{m}</b> minutes of manual comparison.',
 w_still:'Still worth checking yourself: the airline official site, and one major OTA.',
 fare:'Fare',ground:'Ground transport',groundTime:'Travel time',stops:'Stops',channel:'Channel risk',
 tc:'True cost',unknown:'unknown',
 ch_book:'Book',ch_cmp:'Compare / verify',
 ag_only:'(agency named by the data source; no direct link available)',
 no_res:'No suitable option found. Try other dates or relax your limits.',
 ex_stops:'too many stops',ex_ground:'ground transfer exceeds your limit',ex_unknown:'ground cost unknown',
 foot:'Fares are Aviasales cached prices, not live quotes. This system helps you decide; it does not sell tickets.'
}};
var lang='zh',trip='return',profile='balanced',answers={},last=null;
function t(k,v){var s=(I[lang]&&I[lang][k])||k;if(v)for(var x in v)s=s.split('{'+x+'}').join(v[x]);return s}
function apply(){document.documentElement.lang=lang==='zh'?'zh-Hant':'en';
 var e=document.querySelectorAll('[data-i]');for(var i=0;i<e.length;i++){var k=e[i].getAttribute('data-i');if(I[lang][k])e[i].textContent=I[lang][k]}
 $('lz').className=lang==='zh'?'on':'';$('le').className=lang==='en'?'on':'';
 renderQuiz();if(last)render(last)}
$('lz').onclick=function(){lang='zh';apply()};$('le').onclick=function(){lang='en';apply()};

var tb=document.querySelectorAll('.tabs button');
for(var i=0;i<tb.length;i++)tb[i].onclick=function(){
 for(var j=0;j<tb.length;j++)tb[j].className='';this.className='on';
 var x=this.getAttribute('data-tab');
 $('t-go').className=x==='go'?'':'hidden';$('t-me').className=x==='me'?'':'hidden';$('t-sig').className=x==='sig'?'':'hidden'};
var trb=document.querySelectorAll('.trip button');
for(var i=0;i<trb.length;i++)trb[i].onclick=function(){
 for(var j=0;j<trb.length;j++)trb[j].className='';this.className='on';
 trip=this.getAttribute('data-trip');$('retW').style.display=trip==='return'?'block':'none'};
var pb=document.querySelectorAll('.profs button');
for(var i=0;i<pb.length;i++)pb[i].onclick=function(){
 for(var j=0;j<pb.length;j++)pb[j].className='';this.className='on';
 profile=this.getAttribute('data-p');savePrefs()};

var QUIZ=[];
fetch('/api/prefs?uid='+UID).then(function(r){return r.json()}).then(function(d){
 QUIZ=d.quiz||[];
 if(d.saved){profile=d.saved.profile||'balanced';answers=d.saved.answers||{};
  var b=document.querySelectorAll('.profs button');
  for(var i=0;i<b.length;i++)b[i].className=b[i].getAttribute('data-p')===profile?'on':''}
 renderQuiz();showWeights(d.weights)});

function renderQuiz(){
 var box=$('quiz');if(!box)return;box.innerHTML='';
 QUIZ.forEach(function(q){
  var el=document.createElement('div');el.className='q';
  var a=answers[q.id];
  el.innerHTML='<div class="qt">'+(lang==='zh'?q.zh:q.en)+'</div><div class="qb">'+
   '<button data-v="1" class="'+(a===true?'on':'')+'">'+t('yes')+'</button>'+
   '<button data-v="0" class="'+(a===false?'on':'')+'">'+t('no')+'</button></div>';
  var bs=el.querySelectorAll('.qb button');
  for(var i=0;i<bs.length;i++)bs[i].onclick=(function(v){return function(){
   answers[q.id]=(v==='1');renderQuiz();savePrefs()}})(bs[i].getAttribute('data-v'));
  box.appendChild(el)})}

function savePrefs(){
 fetch('/api/prefs?uid='+UID,{method:'POST',headers:{'Content-Type':'application/json'},
  body:JSON.stringify({profile:profile,answers:answers})})
 .then(function(r){return r.json()}).then(function(d){showWeights(d.weights)})}

function showWeights(w){
 if(!w)return;var b=$('wbox');if(!b)return;
 b.innerHTML='<div style="font-size:.74rem;color:var(--dim);line-height:2">'+
  (lang==='zh'?'由你嘅答案推算:':'Derived from your answers:')+'<br>'+
  (lang==='zh'?'時間價值':'Time value')+' ≈ HK$'+w.timeValue+(lang==='zh'?'/小時':'/hr')+'<br>'+
  (lang==='zh'?'每次轉機':'Per stop')+' ≈ HK$'+w.stopPenalty+'<br>'+
  (lang==='zh'?'官網溢價上限':'Airline-direct premium')+' ≈ HK$'+w.channelPremium+'</div>'}

loadGround();
function loadGround(){
 fetch('/api/ground?uid='+UID).then(function(r){return r.json()}).then(function(d){
  var l=$('g-list');if(!l)return;l.innerHTML='';
  Object.keys(d.ground||{}).forEach(function(c){
   var g=d.ground[c];var el=document.createElement('div');
   el.style.cssText='display:flex;justify-content:space-between;align-items:center;padding:8px 0;border-bottom:1px solid var(--line);font-size:.8rem';
   el.innerHTML='<span><b>'+c+'</b> · HK$'+g.costHKD+' · '+g.minutes+'min</span>';
   var x=document.createElement('button');x.textContent='×';
   x.style.cssText='background:none;border:none;color:var(--hot);cursor:pointer;font-size:1.1rem';
   x.onclick=function(){fetch('/api/ground?uid='+UID,{method:'POST',headers:{'Content-Type':'application/json'},
    body:JSON.stringify({code:c,remove:true})}).then(loadGround)};
   el.appendChild(x);l.appendChild(el)})})}
$('g-add').onclick=function(){
 var c=$('g-code').value.trim().toUpperCase();if(c.length!==3)return;
 fetch('/api/ground?uid='+UID,{method:'POST',headers:{'Content-Type':'application/json'},
  body:JSON.stringify({code:c,costHKD:$('g-cost').value,minutes:$('g-min').value})})
 .then(function(){$('g-code').value='';$('g-cost').value='';$('g-min').value='';loadGround()})};

function money(v,c){try{return new Intl.NumberFormat(lang==='zh'?'zh-HK':'en-US',{style:'currency',currency:c||'HKD',maximumFractionDigits:0}).format(v)}catch(e){return (c||'')+v}}

$('go').onclick=function(){
 var o=$('origin').value.trim().toUpperCase(),d=$('dest').value.trim().toUpperCase();
 if(o.length!==3||d.length!==3){setS('IATA x3',true);return}
 if(!$('dep').value){setS('date',true);return}
 var p=new URLSearchParams();
 p.set('uid',UID);p.set('origin',o);p.set('destination',d);p.set('trip',trip);
 p.set('departDate',$('dep').value);
 if(trip==='return'&&$('ret').value)p.set('returnDate',$('ret').value);
 p.set('currency',$('cur').value);p.set('pax',$('pax').value);
 p.set('distance',$('dist').value);p.set('profile',profile);
 setS(t('researching'));$('go').disabled=true;$('out').innerHTML='';
 fetch('/api/orchestrate?'+p.toString()).then(function(r){return r.json()}).then(function(d){
  $('go').disabled=false;
  if(d.error){setS(d.error,true);return}
  setS('');last=d;render(d);explain(d)})
 .catch(function(e){$('go').disabled=false;setS(e.message,true)})};
function setS(m,e){$('status').textContent=m||'';$('status').className='status'+(e?' err':'')}

function render(d){
 var box=$('out');box.innerHTML='';
 function eyebrow(k){var e=document.createElement('div');e.className='eyebrow';e.textContent=t(k);box.appendChild(e)}

 // work saved
 var ws=d.workSaved||{};
 var sv=document.createElement('div');sv.className='saved';
 sv.innerHTML=t('w_saved',{n:ws.checksRun||0,m:ws.manualEquivalent||0})+
  '<div style="color:var(--dim);font-size:.74rem;margin-top:6px">'+t('w_still')+'</div>';
 box.appendChild(sv);

 // confidence — three separate numbers
 eyebrow('e_conf');
 var cf=d.confidence||{};var cb=document.createElement('div');cb.className='conf';
 cb.innerHTML=
  '<div class="cbox"><div class="k">'+t('c_price')+'</div><div class="v">'+t('c_cached')+'</div><div class="s">'+t('c_cached_s')+'</div></div>'+
  '<div class="cbox"><div class="k">'+t('c_comp')+'</div><div class="v">'+(cf.completeness?cf.completeness.pct:0)+'%</div><div class="s">'+
   t('c_steps',{a:cf.completeness?cf.completeness.ranSteps:0,b:cf.completeness?cf.completeness.plannedSteps:0})+'</div></div>'+
  '<div class="cbox"><div class="k">'+t('c_time')+'</div><div class="v">'+
   (cf.timing&&cf.timing.level!=='none'?cf.timing.level:t('c_none'))+'</div><div class="s">'+
   t('c_samples',{n:cf.timing?cf.timing.samples:0})+'</div></div>';
 box.appendChild(cb);

 // agent log — what ran and WHY NOT
 eyebrow('e_plan');
 (d.log||[]).forEach(function(s){
  var ic=s.status==='ok'?'✓':(s.status==='empty'?'○':(s.status==='skipped'?'—':'✕'));
  var el=document.createElement('div');el.className='step '+s.status;
  var why='';
  if(s.whyNot&&d.whyNot&&d.whyNot[s.whyNot])why='<div class="why">'+(lang==='zh'?d.whyNot[s.whyNot].zh:d.whyNot[s.whyNot].en)+'</div>';
  el.innerHTML='<span class="ic">'+ic+'</span><span>'+(lang==='zh'?s.zh:s.en)+why+'</span>'+
   (s.found?'<span class="cnt">'+s.found+'</span>':'');
  box.appendChild(el)});
 var cn=document.createElement('div');cn.className='note';
 cn.textContent=lang==='zh'?d.whyNot.carrier_not_enumerable.zh:d.whyNot.carrier_not_enumerable.en;
 box.appendChild(cn);

 // radar
 var r=d.radar;
 if(r){
  eyebrow('e_radar');
  var rb=document.createElement('div');rb.className='radar';
  var h='<div class="rv '+r.verdict+'">'+t('v_'+r.verdict)+'</div>';
  if(r.canPredict){
   h+='<div style="font-size:.82rem;color:var(--dim)">'+t('r_pct',{n:r.percentile})+'</div>'+
    '<div class="bar"><div class="fill" style="width:100%"></div><div class="mk" style="left:'+Math.min(98,Math.max(0,r.percentile))+'%"></div></div>'+
    '<div class="rmeta"><span>'+t('r_range',{lo:money(r.lowestSeen,d.query.currency),med:money(r.medianSeen,d.query.currency),hi:money(r.highestSeen,d.query.currency)})+'</span>'+
    '<span>'+t('r_trend',{n:(r.trendPct>0?'+':'')+r.trendPct})+'</span><span>'+r.samples+'d</span></div>';
  }else{
   h+='<div style="font-size:.82rem;color:var(--dim)">'+t('r_none',{n:r.samples,m:r.needed})+'</div>';
  }
  rb.innerHTML=h;box.appendChild(rb);
  if(r.signals&&r.signals.length){
   var sn=document.createElement('div');sn.className='note';sn.textContent=t('r_sig');box.appendChild(sn);
   var so=$('sigout');so.innerHTML='';so.className='';
   r.signals.forEach(function(s){
    var e=document.createElement('div');e.className='sig';
    e.innerHTML='<a href="'+s.url+'" target="_blank" rel="noopener">'+String(s.title).replace(/</g,'&lt;')+'</a><div class="m">'+s.source+'</div>';
    so.appendChild(e)})}
 }

 // AI slot
 var ab=document.createElement('div');ab.id='aib';box.appendChild(ab);

 // offers
 var offers=d.offers||[];
 if(!offers.length){var e=document.createElement('div');e.className='empty';e.textContent=t('no_res');box.appendChild(e);return}
 eyebrow('e_all');
 offers.forEach(function(o,idx){box.appendChild(offerCard(o,idx===0,d.query.currency))});

 if(d.needsInput&&d.needsInput.length){
  eyebrow('e_need');
  var nn=document.createElement('div');nn.className='note';nn.textContent=t('n_need');box.appendChild(nn);
  d.needsInput.forEach(function(o){
   var el=document.createElement('div');el.className='step empty';
   el.innerHTML='<span class="ic">?</span><span>'+o.origin+'→'+o.destination+' '+money(o.priceTotal,d.query.currency)+
    '<div class="why">'+t('ex_unknown')+'</div></span>';
   box.appendChild(el)})}

 if(d.excluded&&d.excluded.length){
  eyebrow('e_ex');
  d.excluded.forEach(function(o){
   var el=document.createElement('div');el.className='step skipped';
   el.innerHTML='<span class="ic">—</span><span>'+o.origin+'→'+o.destination+' '+money(o.priceTotal,d.query.currency)+
    '<div class="why">'+(o.ineligibleWhy==='exceeds_max_stops'?t('ex_stops'):t('ex_ground'))+'</div></span>';
   box.appendChild(el)})}
}

function offerCard(o,best,cur){
 var el=document.createElement('div');el.className='card'+(best?' best':'');
 var bits=[];
 if(o.departDate)bits.push('<span>'+o.departDate+(o.returnDate?(' → '+o.returnDate):'')+'</span>');
 if(o.stops!=null)bits.push('<span>'+(o.stops===0?(lang==='zh'?'直航':'Direct'):o.stops+(lang==='zh'?' 轉':' stop'))+'</span>');
 if(o.airlineName)bits.push('<span>'+o.airlineName+'</span>');
 bits.push('<span class="tag tag-'+o.via+'">'+o.via.replace('_',' ')+'</span>');

 var work='';
 (o.costParts||[]).forEach(function(p){
  if(p.unknown){work+='<div class="unk">'+t(p.k)+': '+t('unknown')+'</div>';return}
  if(p.k==='fare'){work+='<div>'+t('fare')+': '+money(p.v,cur)+'</div>';return}
  work+='<div class="neg">+ '+t(p.k)+': '+money(p.v,cur)+(p.hours?(' ('+p.hours.toFixed(1)+'h)'):'')+'</div>'});
 work+='<div style="border-top:1px solid var(--line);margin-top:5px;padding-top:5px"><b>'+t('tc')+': '+money(o.trueCost,cur)+'</b></div>';

 var bk=(o.channels||[]).filter(function(c){return c.kind==='book'});
 var cp=(o.channels||[]).filter(function(c){return c.kind!=='book'});
 var ch='<div class="ch"><div class="chl">'+t('ch_book')+'</div><div class="chw">';
 bk.forEach(function(c){
  var nm=lang==='zh'?c.nameZh:c.nameEn;
  if(c.url)ch+='<a class="b book" href="'+c.url+'" target="_blank" rel="noopener">'+nm+'</a>';
  else ch+='<span class="b dis" title="'+t('ag_only')+'">'+nm+'</span>'});
 if(!bk.length)ch+='<span class="b dis">—</span>';
 ch+='</div><div class="chl" style="margin-top:9px">'+t('ch_cmp')+'</div><div class="chw">';
 cp.forEach(function(c){ch+='<a class="b cmp" href="'+c.url+'" target="_blank" rel="noopener">'+(lang==='zh'?c.nameZh:c.nameEn)+'</a>'});
 ch+='</div></div>';

 el.innerHTML='<div class="ctop"><div><div class="route">'+o.origin+'<span class="ar">→</span>'+o.destination+'</div>'+
  '<div class="meta">'+bits.join('')+'</div></div>'+
  '<div class="price"><div class="p">'+money(o.priceTotal,cur)+'</div><div class="tc">'+t('tc')+' '+money(o.trueCost,cur)+'</div></div></div>'+
  '<div class="work">'+work+'</div>'+ch;
 return el}

function explain(d){
 var b=$('aib');if(!b)return;
 b.innerHTML='<div class="ai"><div class="l">AI</div>…</div>';
 fetch('/api/explain',{method:'POST',headers:{'Content-Type':'application/json'},
  body:JSON.stringify({best:(d.offers||[])[0]||null,radar:d.radar,confidence:d.confidence,weights:d.weights,lang:lang})})
 .then(function(r){return r.json()}).then(function(a){
  b.innerHTML='<div class="ai"><div class="l">AI</div>'+String(a.text||'').replace(/</g,'&lt;')+'</div>'})
 .catch(function(){b.innerHTML=''})}

(function(){var d=new Date();d.setDate(d.getDate()+21);var r=new Date(d);r.setDate(r.getDate()+5);
 $('dep').value=d.toISOString().slice(0,10);$('ret').value=r.toISOString().slice(0,10)})();
apply();
if('serviceWorker' in navigator){navigator.serviceWorker.register('/sw.js').catch(function(){})}
})();
</script></body></html>`;
